spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/replyiq_test
    username: ${DB_USERNAME:stephaniedugas}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create-drop
