<script setup>
</script>

<template>
  <div class="min-h-screen bg-[#0f1320] text-gray-300">
    <div class="max-w-3xl mx-auto px-6 py-16">
      <h1 class="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
      <p class="text-sm text-gray-500 mb-10">Last updated: May 9, 2026</p>

      <div class="space-y-8 text-sm leading-relaxed">
        <section>
          <h2 class="text-lg font-semibold text-white mb-3">1. Introduction</h2>
          <p><strong class="text-white">Erie Apps LLC</strong> ("Company," "we," "us," or "our") operates the ReplyIQ application (the "Service"). This Privacy Policy explains how we collect, use, disclose, and protect your information when you use our Service.</p>
          <p class="mt-2">By using the Service, you consent to the data practices described in this policy. If you do not agree, please do not use the Service.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">2. Information We Collect</h2>

          <h3 class="text-sm font-semibold text-white mt-4 mb-2">2.1 Information You Provide</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li><strong class="text-white">Account information:</strong> Name, email address, and password when you create an account</li>
            <li><strong class="text-white">Payment information:</strong> Billing details processed through Stripe. We do not store credit card numbers on our servers.</li>
            <li><strong class="text-white">Business information:</strong> Business names, addresses, and location data from your connected Google Business Profile</li>
          </ul>

          <h3 class="text-sm font-semibold text-white mt-4 mb-2">2.2 Information from Google Business Profile</h3>
          <p>When you connect your Google Business Profile, we access and store:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>Business location names and addresses</li>
            <li>Customer reviews (reviewer name, star rating, review text, date posted)</li>
            <li>Your existing review replies</li>
            <li>OAuth access tokens and refresh tokens (stored securely to maintain your connection)</li>
          </ul>
          <p class="mt-2">We only access the data necessary to provide the Service. We do not access your personal Google account data, Gmail, Google Drive, or any other Google services beyond your Business Profile.</p>

          <h3 class="text-sm font-semibold text-white mt-4 mb-2">2.3 Information Generated by the Service</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>AI-generated review replies created using Anthropic's Claude API</li>
            <li>Reply approval and posting history</li>
            <li>Dashboard analytics and usage metrics</li>
          </ul>

          <h3 class="text-sm font-semibold text-white mt-4 mb-2">2.4 Automatically Collected Information</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li>IP address and browser type</li>
            <li>Device information and operating system</li>
            <li>Usage data (pages visited, features used, timestamps)</li>
          </ul>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">3. How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>Provide, maintain, and improve the Service</li>
            <li>Monitor your Google Business Profile for new reviews</li>
            <li>Generate AI-powered reply suggestions using Anthropic's Claude API</li>
            <li>Post approved replies to your Google Business Profile on your behalf</li>
            <li>Process subscription payments through Stripe</li>
            <li>Send you service-related communications (account notifications, billing alerts)</li>
            <li>Respond to your support requests</li>
            <li>Detect and prevent fraud or abuse</li>
          </ul>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">4. How We Share Your Information</h2>
          <p>We do not sell your personal information. We share information only in the following circumstances:</p>

          <h3 class="text-sm font-semibold text-white mt-4 mb-2">4.1 Third-Party Service Providers</h3>
          <ul class="list-disc pl-6 space-y-1">
            <li><strong class="text-white">Google (Business Profile API):</strong> To read reviews and post replies on your behalf. Subject to <a href="https://policies.google.com/privacy" class="text-emerald-400 hover:underline" target="_blank" rel="noopener">Google's Privacy Policy</a>.</li>
            <li><strong class="text-white">Anthropic (Claude API):</strong> Review text and business context are sent to generate reply suggestions. Subject to <a href="https://www.anthropic.com/privacy" class="text-emerald-400 hover:underline" target="_blank" rel="noopener">Anthropic's Privacy Policy</a>. Anthropic does not use API inputs for model training.</li>
            <li><strong class="text-white">Stripe:</strong> For payment processing and subscription management. Subject to <a href="https://stripe.com/privacy" class="text-emerald-400 hover:underline" target="_blank" rel="noopener">Stripe's Privacy Policy</a>.</li>
          </ul>

          <h3 class="text-sm font-semibold text-white mt-4 mb-2">4.2 Legal Requirements</h3>
          <p>We may disclose your information if required to do so by law, regulation, legal process, or governmental request.</p>

          <h3 class="text-sm font-semibold text-white mt-4 mb-2">4.3 Business Transfers</h3>
          <p>In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of the transaction. We will notify you of any such change.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">5. Data Security</h2>
          <p>We implement industry-standard security measures to protect your information, including:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>HTTPS encryption for all data in transit</li>
            <li>Secure storage of OAuth tokens and credentials</li>
            <li>Password hashing using BCrypt</li>
            <li>JWT-based authentication with expiring tokens</li>
          </ul>
          <p class="mt-2">While we strive to protect your information, no method of electronic transmission or storage is 100% secure. We cannot guarantee absolute security.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">6. Data Retention</h2>
          <p>We retain your information for as long as your account is active or as needed to provide the Service. Specifically:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li><strong class="text-white">Account data:</strong> Retained until you delete your account</li>
            <li><strong class="text-white">Review data:</strong> Retained while your account is active. Deleted 90 days after account closure or subscription lapse.</li>
            <li><strong class="text-white">OAuth tokens:</strong> Deleted immediately upon disconnecting your Google Business Profile or closing your account</li>
            <li><strong class="text-white">Payment records:</strong> Retained as required by applicable tax and financial regulations</li>
          </ul>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">7. Your Rights</h2>
          <p>Depending on your jurisdiction, you may have the following rights regarding your personal information:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li><strong class="text-white">Access:</strong> Request a copy of your personal data</li>
            <li><strong class="text-white">Correction:</strong> Request correction of inaccurate data</li>
            <li><strong class="text-white">Deletion:</strong> Request deletion of your account and associated data</li>
            <li><strong class="text-white">Portability:</strong> Request your data in a portable format</li>
            <li><strong class="text-white">Revoke consent:</strong> Disconnect your Google Business Profile at any time</li>
          </ul>
          <p class="mt-2">To exercise any of these rights, contact us at <span class="text-white">stephanie@erie-apps.com</span>.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">8. Google API Services User Data Policy</h2>
          <p>ReplyIQ's use and transfer of information received from Google APIs adheres to the <a href="https://developers.google.com/terms/api-services-user-data-policy" class="text-emerald-400 hover:underline" target="_blank" rel="noopener">Google API Services User Data Policy</a>, including the Limited Use requirements.</p>
          <p class="mt-2">We only use Google user data to provide and improve the Service. We do not use Google user data for advertising purposes. We do not sell Google user data to third parties.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">9. Children's Privacy</h2>
          <p>The Service is not intended for use by individuals under the age of 18. We do not knowingly collect personal information from children. If we become aware that we have collected information from a child, we will delete it promptly.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">10. Changes to This Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on this page and updating the "Last updated" date. Continued use of the Service after changes constitutes acceptance of the updated policy.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">11. Contact Us</h2>
          <p>If you have questions or concerns about this Privacy Policy or our data practices, contact us at:</p>
          <p class="mt-2 text-white">Erie Apps LLC<br>Email: stephanie@erie-apps.com</p>
        </section>
      </div>
    </div>
  </div>
</template>
