<script setup>
</script>

<template>
  <div class="min-h-screen bg-[#0f1320] text-gray-300">
    <div class="max-w-3xl mx-auto px-6 py-16">
      <h1 class="text-3xl font-bold text-white mb-2">Terms of Service</h1>
      <p class="text-sm text-gray-500 mb-10">Last updated: May 9, 2026</p>

      <div class="space-y-8 text-sm leading-relaxed">
        <section>
          <h2 class="text-lg font-semibold text-white mb-3">1. Agreement to Terms</h2>
          <p>These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and <strong class="text-white">Erie Apps LLC</strong> ("Company," "we," "us," or "our"), governing your access to and use of the ReplyIQ application and related services (collectively, the "Service").</p>
          <p class="mt-2">By creating an account or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
          <p>ReplyIQ is a software-as-a-service (SaaS) platform that helps local business owners manage and respond to Google Business Profile reviews. The Service includes:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>Connecting to your Google Business Profile via Google OAuth 2.0</li>
            <li>Automated monitoring and retrieval of customer reviews</li>
            <li>AI-powered reply generation using Anthropic's Claude API</li>
            <li>Tools to review, edit, approve, and post replies to Google</li>
            <li>Dashboard analytics for review monitoring</li>
          </ul>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">3. Account Registration</h2>
          <p>You must provide accurate, complete, and current information when creating an account. You are responsible for safeguarding your account credentials and for all activity under your account. You must notify us immediately of any unauthorized use of your account.</p>
          <p class="mt-2">You must be at least 18 years of age and have the legal authority to enter into these Terms on behalf of yourself or the business you represent.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">4. Google Business Profile Authorization</h2>
          <p>To use the Service, you must authorize ReplyIQ to access your Google Business Profile account via Google OAuth 2.0. By granting this authorization, you represent and warrant that:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>You are the owner or authorized manager of the Google Business Profile(s) you connect</li>
            <li>You have the authority to post replies to reviews on behalf of the connected business(es)</li>
            <li>You consent to ReplyIQ reading your reviews, business information, and posting replies on your behalf</li>
          </ul>
          <p class="mt-2">You may revoke this authorization at any time through your Google Account settings. Revoking access will prevent ReplyIQ from monitoring or replying to your reviews.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">5. AI-Generated Content</h2>
          <p>ReplyIQ uses Anthropic's Claude AI to generate suggested replies to reviews. You acknowledge and agree that:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>AI-generated replies are suggestions and may require editing before posting</li>
            <li>You are solely responsible for reviewing, approving, and posting all replies — whether generated by AI or written manually</li>
            <li>Erie Apps LLC is not liable for any consequences arising from replies posted to your Google Business Profile, including AI-generated content</li>
            <li>AI-generated content may not always be accurate, appropriate, or suitable for your specific business context</li>
          </ul>
          <p class="mt-2">If you enable the "Auto-Post" feature, replies will be posted to Google automatically without manual review. You assume full responsibility for all auto-posted content.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">6. Subscription and Payment</h2>
          <p>The Service is offered on a subscription basis at <strong class="text-white">$19.99 per month</strong>. All payments are processed securely through <strong class="text-white">Stripe</strong>, our third-party payment processor.</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li><strong class="text-white">Free Trial:</strong> New accounts receive a 7-day free trial. No credit card is required to start the trial.</li>
            <li><strong class="text-white">Billing:</strong> After the trial period, your subscription will begin and you will be billed monthly. By subscribing, you authorize recurring charges to your payment method.</li>
            <li><strong class="text-white">Cancellation:</strong> You may cancel your subscription at any time through the Stripe billing portal. Cancellation takes effect at the end of your current billing period. No refunds are provided for partial months.</li>
            <li><strong class="text-white">Lapsed Subscriptions:</strong> If your subscription lapses or payment fails, the review monitoring agent will pause. Your data will be preserved for 90 days, after which it may be deleted.</li>
          </ul>
          <p class="mt-2">Erie Apps LLC reserves the right to change subscription pricing with 30 days' notice to active subscribers.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">7. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li>Violate any applicable law, regulation, or third-party rights</li>
            <li>Post fraudulent, misleading, defamatory, or harmful replies</li>
            <li>Attempt to reverse-engineer, decompile, or disassemble the Service</li>
            <li>Interfere with or disrupt the Service or its infrastructure</li>
            <li>Use the Service on behalf of a business you do not own or have authority to manage</li>
            <li>Resell, sublicense, or redistribute the Service without written permission</li>
          </ul>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">8. Intellectual Property</h2>
          <p>The Service, including its design, code, features, and documentation, is owned by Erie Apps LLC and protected by intellectual property laws. Your subscription grants you a limited, non-exclusive, non-transferable license to use the Service for your business purposes.</p>
          <p class="mt-2">You retain ownership of all content you provide, including business information and review replies you compose or approve.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">9. Third-Party Services</h2>
          <p>The Service integrates with the following third-party services:</p>
          <ul class="list-disc pl-6 mt-2 space-y-1">
            <li><strong class="text-white">Google Business Profile API</strong> — for reading reviews and posting replies</li>
            <li><strong class="text-white">Anthropic Claude API</strong> — for AI-powered reply generation</li>
            <li><strong class="text-white">Stripe</strong> — for payment processing and subscription management</li>
          </ul>
          <p class="mt-2">Your use of these third-party services is subject to their respective terms of service and privacy policies. Erie Apps LLC is not responsible for the availability, accuracy, or conduct of any third-party service.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">10. Limitation of Liability</h2>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, ERIE APPS LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, BUSINESS OPPORTUNITIES, OR GOODWILL, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.</p>
          <p class="mt-2">OUR TOTAL LIABILITY FOR ALL CLAIMS ARISING FROM OR RELATED TO THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">11. Disclaimer of Warranties</h2>
          <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">12. Termination</h2>
          <p>We may suspend or terminate your access to the Service at any time for violation of these Terms or for any other reason at our sole discretion. Upon termination, your right to use the Service ceases immediately. Sections 8, 10, 11, and 13 survive termination.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">13. Governing Law</h2>
          <p>These Terms are governed by and construed in accordance with the laws of the State of Pennsylvania, without regard to conflict of law principles. Any disputes arising from these Terms shall be resolved in the courts located in Erie County, Pennsylvania.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">14. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. We will notify active users of material changes via email or through the Service. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.</p>
        </section>

        <section>
          <h2 class="text-lg font-semibold text-white mb-3">15. Contact</h2>
          <p>If you have questions about these Terms, contact us at:</p>
          <p class="mt-2 text-white">Erie Apps LLC<br>Email: support@erieapps.com</p>
        </section>
      </div>
    </div>
  </div>
</template>
